<?php defined('ABSPATH') or die(); 

function adblocks2_counter_fields() {
	if( function_exists('acf_add_local_field_group') ):
		
		acf_add_local_field_group(array(
			'key' => 'group_654385a8caf18',
			'title' => __('Counter Block', 'adblocks2'),
			'fields' => array(
				array(
					'key' => 'field_6543860582bc0',
					'label' => __('Number of columns', 'adblocks2'),
					'name' => 'columns',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'col3' => __('3 columns', 'adblocks2'),
						'col4' => __('4 columns', 'adblocks2'),
						'col6' => __('6 columns', 'adblocks2'),
					),
					'default_value' => 'col3',
					'return_format' => 'value',
					'allow_null' => 0,
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_654385a982bbc',
					'label' => __('Counters', 'adblocks2'),
					'name' => 'counters',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => __('Add a counter', 'adblocks2'),
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_654385cf82bbd',
							'label' => __('Number', 'adblocks2'),
							'name' => 'number',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_654385a982bbc',
						),
						array(
							'key' => 'field_654385df82bbe',
							'label' => __('Increment', 'adblocks2'),
							'name' => 'increment',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_654385a982bbc',
						),
						array(
							'key' => 'field_654385ea82bbf',
							'label' => __('Legend', 'adblocks2'),
							'name' => 'legend',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_654385a982bbc',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/counter-2',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		));
		
	endif;
}
add_action('acf/init', 'adblocks2_counter_fields');