<?php defined('ABSPATH') or die(); 

function adblocks2_gallery_fields() {
	if( function_exists('acf_add_local_field_group') ):
		
		acf_add_local_field_group( array(
			'key' => 'group_657825ddbedec',
			'title' => __( 'Gallery Block', 'adblocks2' ),
			'fields' => array(
				array(
					'key' => 'field_6579b320f4bca',
					'label' => __( 'Number of columns', 'adblocks2' ),
					'name' => 'cols',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'col-1' => __( '1', 'adblocks2' ),
						'col-2' => __( '2', 'adblocks2' ),
						'col-3' => __( '3', 'adblocks2' ),
						'col-4' => __( '4', 'adblocks2' ),
						'col-5' => __( '5', 'adblocks2' ),
						'col-6' => __( '6', 'adblocks2' ),
						'col-7' => __( '7', 'adblocks2' ),
						'col-8' => __( '8', 'adblocks2' ),
					),
					'default_value' => 'col-3',
					'return_format' => 'value',
					'allow_null' => 0,
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_65789431d1dc3',
					'label' => __( 'Pictures', 'adblocks2' ),
					'name' => 'pictures',
					'aria-label' => '',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'insert' => 'append',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_6579b67076694',
					'label' => __( 'Picture size', 'adblocks2' ),
					'name' => 'size',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'thumbnail' => __( 'Thumbnail', 'adblocks2' ),
						'medium' => __( 'Medium', 'adblocks2' ),
						'large' => __( 'Large', 'adblocks2' ),
					),
					'default_value' => 'thumbnail',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_657825de35047',
					'label' => __( 'Enlarge pictures', 'adblocks2' ),
					'name' => 'enlarge',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => __( 'Enlarge with Fancybox', 'adblocks2' ),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
				),
				array(
					'key' => 'field_65785bae91941',
					'label' => __( 'Hidden caption', 'adblocks2' ),
					'name' => 'inside',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => __( 'Revealed on mouse over and focus', 'adblocks2' ),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/gallery-2',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		));
		
	endif;
}
add_action('acf/init', 'adblocks2_gallery_fields');