<?php defined('ABSPATH') or die(); 

function adblocks2_carousel_fields() {
	if( function_exists('acf_add_local_field_group') ):
		
		acf_add_local_field_group( array(
			'key' => 'group_6548ed7b3c43f',
			'title' => __('Carousel Block', 'adblocks2'),
			'fields' => array(
				array(
					'key' => 'field_6548ede56e286',
					'label' => __('Type of elements', 'adblocks2'),
					'name' => 'type',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'custom' => __('Custom content', 'adblocks2'),
						'posts' => __('Exisiting posts', 'adblocks2'),
					),
					'default_value' => 'custom',
					'return_format' => 'value',
					'allow_null' => 0,
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_6548ed7b6e285',
					'label' => __('Visible elements', 'adblocks2'),
					'name' => 'elems',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'one' => __('1', 'adblocks2'),
						'two' => __('2', 'adblocks2'),
						'three' => __('3', 'adblocks2'),
						'four' => __('4', 'adblocks2'),
						'five' => __('5', 'adblocks2'),
						'six' => __('6', 'adblocks2'),
					),
					'default_value' => 'three',
					'return_format' => 'value',
					'allow_null' => 0,
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_67d40a2687842',
					'label' => __( 'Slides to scroll', 'adblocks2' ),
					'name' => 'slides_scroll',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'one' => __( '1', 'adblocks2' ),
						'two' => __( '2', 'adblocks2' ),
						'three' => __( '3', 'adblocks2' ),
						'four' => __( '4', 'adblocks2' ),
						'five' => __( '5', 'adblocks2' ),
						'six' => __( '6', 'adblocks2' ),
					),
					'default_value' => '',
					'return_format' => 'value',
					'allow_null' => 0,
					'allow_in_bindings' => 1,
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_6549e42ea2201',
					'label' => __('Fade or Slide', 'adblocks2'),
					'name' => 'fade',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => __('Fade', 'adblocks2'),
					'ui_off_text' => __('Slide', 'adblocks2'),
					'ui' => 1,
				),
				array(
					'key' => 'field_6549e42ea26f9',
					'label' => __('Autoplay', 'adblocks2'),
					'name' => 'autoplay',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
				),
				array(
					'key' => 'field_654b2737c52ed',
					'label' => __('Slide duration', 'adblocks2'),
					'name' => 'autospeed',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => __('Slide duration in Autoplay mode', 'adblocks2'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 3000,
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6549e385a26f6',
					'label' => __('Speed', 'adblocks2'),
					'name' => 'speed',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => __('Transition speed between two slides', 'adblocks2'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1000,
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6549e3a7a26f7',
					'label' => __('Display arrows', 'adblocks2'),
					'name' => 'arrows',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
				),
				array(
					'key' => 'field_6549e3c4a26f8',
					'label' => __('Display dots', 'adblocks2'),
					'name' => 'dots',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
				),
				array(
					'key' => 'field_6548f6a104291',
					'label' => __('Posts', 'adblocks2'),
					'name' => 'the_posts',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6548ede56e286',
								'operator' => '==',
								'value' => 'posts',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'post_status' => '',
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
						1 => 'post_type',
						2 => 'taxonomy',
					),
					'return_format' => 'object',
					'min' => '',
					'max' => '',
					'elements' => array(
						0 => 'featured_image',
					),
					'bidirectional' => 0,
					'bidirectional_target' => array(
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/carousel-2',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		) );
		
	endif;
}
add_action('acf/init', 'adblocks2_carousel_fields');